import class Foundation.Bundle
import struct Foundation.URL
import struct Foundation.Data

public enum GGSource : String, CaseIterable{
    case _7zip_png = "7zip.png"
    case airports_csv = "airports.csv"
    case annual_precip_json = "annual-precip.json"
    case anscombe_json = "anscombe.json"
    case barley_json = "barley.json"
    case birdstrikes_csv = "birdstrikes.csv"
    case budget_json = "budget.json"
    case budgets_json = "budgets.json"
    case burtin_json = "burtin.json"
    case cars_json = "cars.json"
    case co2_concentration_csv = "co2-concentration.csv"
    case countries_json = "countries.json"
    case crimea_json = "crimea.json"
    case disasters_csv = "disasters.csv"
    case driving_json = "driving.json"
    case earthquakes_json = "earthquakes.json"
    case ffox_png = "ffox.png"
    case flare_dependencies_json = "flare-dependencies.json"
    case flare_json = "flare.json"
    case flights_10k_json = "flights-10k.json"
    case flights_200k_arrow = "flights-200k.arrow"
    case flights_200k_json = "flights-200k.json"
    case flights_20k_json = "flights-20k.json"
    case flights_2k_json = "flights-2k.json"
    case flights_3m_csv = "flights-3m.csv"
    case flights_5k_json = "flights-5k.json"
    case flights_airport_csv = "flights-airport.csv"
    case football_json = "football.json"
    case gapminder_health_income_csv = "gapminder-health-income.csv"
    case gapminder_json = "gapminder.json"
    case gimp_png = "gimp.png"
    case github_csv = "github.csv"
    case income_json = "income.json"
    case iowa_electricity_csv = "iowa-electricity.csv"
    case jobs_json = "jobs.json"
    case la_riots_csv = "la-riots.csv"
    case londonBoroughs_json = "londonBoroughs.json"
    case londonCentroids_json = "londonCentroids.json"
    case londonTubeLines_json = "londonTubeLines.json"
    case lookup_groups_csv = "lookup_groups.csv"
    case lookup_people_csv = "lookup_people.csv"
    case miserables_json = "miserables.json"
    case monarchs_json = "monarchs.json"
    case movies_json = "movies.json"
    case normal_2d_json = "normal-2d.json"
    case obesity_json = "obesity.json"
    case ohlc_json = "ohlc.json"
    case penguins_json = "penguins.json"
    case points_json = "points.json"
    case political_contributions_json = "political-contributions.json"
    case population_json = "population.json"
    case population_engineers_hurricanes_csv = "population_engineers_hurricanes.csv"
    case seattle_weather_hourly_normals_csv = "seattle-weather-hourly-normals.csv"
    case seattle_weather_csv = "seattle-weather.csv"
    case sp500_2000_csv = "sp500-2000.csv"
    case sp500_csv = "sp500.csv"
    case stocks_csv = "stocks.csv"
    case udistrict_json = "udistrict.json"
    case unemployment_across_industries_json = "unemployment-across-industries.json"
    case unemployment_tsv = "unemployment.tsv"
    case uniform_2d_json = "uniform-2d.json"
    case us_10m_json = "us-10m.json"
    case us_employment_csv = "us-employment.csv"
    case us_state_capitals_json = "us-state-capitals.json"
    case volcano_json = "volcano.json"
    case weather_csv = "weather.csv"
    case weather_json = "weather.json"
    case wheat_json = "wheat.json"
    case windvectors_csv = "windvectors.csv"
    case world_110m_json = "world-110m.json"
    case zipcodes_csv = "zipcodes.csv"


    /// Accesses the data URL for the given sample name
    public var resourceURL: URL? {
        Bundle.module.url(forResource: rawValue, withExtension: nil)
    }

}
