name: GGSpec CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
  schedule:
    # run at 8AM & 8PM UTC
    - cron:  '0 8,20 * * *'

# construct CI latticeflow with cheaper platforms first: Linux & Windows then macOS10, macOS11, iOS, tvOS, watchOS

jobs:    
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test --enable-test-discovery

  macOS10:
    runs-on: macos-10.15
    needs: [Linux] # Linux must pass first
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test

  macOS11:
    runs-on: macos-11.0
    needs: [Linux] # Linux must pass first
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test

  Release:
    runs-on: ubuntu-latest
    needs: [Linux, macOS10, macOS11]

    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            CHANGELOG.md
            RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

